### ISSUE TITLE
Line break missing in SCC reader

### ISSUE THREAD

**Issue by palemieux** [sandflow/ttconv#217]
From SMPTE RP 2052-10, Table B.2

```
Scenarist_SCC V1.0

00:00:02:16	942c

00:00:03:01	9420 13F4 97A1 54E5 73F4 2043 6170 F4E9 EF6E 7380 94D0 97A1 C454 D620 C1E3 E3E5 7373 20D0 F2EF EAE5 E3F4 2C20 57C7 C2C8 ADCE 43C1 CD80 9470 9723 A8F2 756E 6EE9 6E67 20F4 E96D E5BA 2034 206D E96E AE20 31B5 2073 E5E3 AE29 942C 942F

00:00:11:27	9420
```

should result in something along the lines of:

```
<p begin="00:00:05.87" end="00:00:12.98">Test Captions<br/> DTV Access Project, WGBH-NCAM<br/> (running time: 4min. 15 sec.)</p>
```

In the current version, the `<br/>` are missing.

**Comment by valnoel** [comment]
@palemieux 

Actually, the SCC content above gives this in disassembly format:
```
00:00:02:16	{EDM}
00:00:03:01	{RCL}{1308}{TO1}Test Captions{1400}{TO1}DTV Access Project, WGBH-NCAM{1500}{TO3}(running time: 4 min. 15 sec.){EDM}{EOC}
00:00:11:27	{RCL}
```
As we can see:

 * the first line should start at row 13 and at column 9 (8 from the `{1308}` PAC + 1 from the `{TO1}` control code)
 * the second line should start at row 14 and at column 1 (0 from the `{1400}` PAC + 1 from the `{TO1}` control code)
 * the third line should start at row 15 and at column 3 (0 from the `{1500}` PAC + 3 from the `{TO3}` control code)

In the SMPTE RP 2052-10, Table B.2 example, the indentation for the second and the third lines is applied using empty space characters:
```
<p begin="00:00:05.87" end="00:00:12.98">Test Captions<br/> DTV Access Project, WGBH-NCAM<br/>   (running time: 4min. 15 sec.)</p>
```
(with the `xml:space="preserve"` div attribute)

But I don't understand why the indentation of the first line is not set. Maybe a bad copy-paste?

---

However, in our SCC reader, the `<br/>` are set when the lines are contiguous (1 row of difference, same column), which is not the case in this example. They should be set for the following (modified) example: 

```
Scenarist_SCC V1.0

00:00:02:16	942c

00:00:03:01	9420 13F0 97A1 54E5 73F4 2043 6170 F4E9 EF6E 7380 94D0 97A1 C454 D620 C1E3 E3E5 7373 20D0 F2EF EAE5 E3F4 2C20 57C7 C2C8 ADCE 43C1 CD80 9470 9721 A8F2 756E 6EE9 6E67 20F4 E96D E5BA 2034 206D E96E AE20 31B5 2073 E5E3 AE29 942C 942F

00:00:11:27	9420
```
which gives in disassembly:
```
00:00:02:16	{EDM}
00:00:03:01	{RCL}{1300}{TO1}Test Captions{1400}{TO1}DTV Access Project, WGBH-NCAM{1500}{TO1}(running time: 4 min. 15 sec.){EDM}{EOC}
00:00:11:27	{RCL}
```

But the `<br/>` are not set, because it is the last paragraph of the document... (__First issue__)

And with the first example, the current SCC / TTML conversion should actually give a specific `<p>` into a specific region for each line, as described in SMPTE RP 2052-10, Table 6... (__Second issue__)

---

What is you opinion on this? Shouldn't we split this issue into two items?

**Comment by palemieux** [comment]
> But the <br/> are not set, because it is the last paragraph of the document... (First issue)

That sounds like a bug no matter what, right? If so, perhaps, yes, split into its own issue.

> And with the first example, the current SCC / TTML conversion should actually give a specific <p> into a specific region for each line,
> as described in SMPTE RP 2052-10, Table 6... (Second issue)

I am not convinced that creating a separate `p` for each line, as suggested in SMPTE RP 2052-10, is the right approach, since columns could also be used to center or align the text to the right -- as it is probably the case here.

I think the current approach of flowing all text in consecutive lines to a single `p` in a single `region` is ok.

How difficult would it be to try to detect text alignment, i.e. center, right align, left align, etc.? Is it worth it?

**Comment by palemieux** [comment]
> But I don't understand why the indentation of the first line is not set. Maybe a bad copy-paste?

Yes. I am thinking the intent was to center the three lines.

**Comment by valnoel** [comment]
> But the <br/> are not set, because it is the last paragraph of the document... (First issue)

__EDIT:__ this bug is not "because it is the last paragraph of the document" but because this example ends with a `{RCL}` control code (which indicates a new Pop-On caption is going to be defined). So it does not appear for each last paragraph of each SCC input document!
