### ISSUE TITLE
STL: subtitles earlier than TCP should be ignored

### ISSUE THREAD

**Issue by palemieux** [sandflow/ttconv#274]
TTI blocks with a timecode earlier than _Time Code: Start-of-Programme (TCP)_ are used to store metadata and should be ignored by default.

A configuration parameter should be available to override this behavior.

**Comment by xchange11** [comment]
From my view, TCP values need to be taken into account when converting timecode values in EBU STL into media time. The default behaviour should be:
* take the TCP value as a reference for calculating the start of the playtime (so 0s),
* the TCP value needs then be subtracted from all begin and end times,
* because the TCP value may be incorrect, this behaviour can be switched off.

In addition, the user should have the option to apply a self-chosen "offset" that is subtracted from all begin and end times. In this case, the TCP value will be ignored.

In both cases (substracting TCP from GSI or a "self-chosen" TCP) every content with timecodes less than this "offset" will be discarded.

In some operational scenarios, it may be relevant to view content information on-screen that has been stored with a timecode that is less than the TCP (so it does not go on air). This content is mostly metadata. Therefore, it should be possible that an EBU-STL file converts all timecodes and content (e.g., switching off the default behaviour of TCP detection and not providing a self-chosen offset).
