### ISSUE TITLE
Option to remove all TTML element tags

### ISSUE THREAD

**Issue by sh-smpte** [sandflow/ttconv#389]
Could we please have an option to remove all TTML element tags when converting from TTML to vtt and srt?

**Comment by cconcolato** [comment]
I'm not sure I understand the request. Can you provide an example?

**Comment by palemieux** [comment]
I think the idea is to have the option to remove all styling from the input file.

@sh-smpte Is that correct?

I am thinking maybe adding a `--input_filter <filter_name>` option to the command line.

One such filter would be `remove_all_styles`.

**Comment by sh-smpte** [comment]
Yes, correct. For example, when I convert some of my TTML to vtt, there are lines with styling below remains in the conversion result:

<i> [Text] </i>
<i> [Text] </i><i> [Text] </i>

**Comment by palemieux** [comment]
Couple of observations upon closer observation:

- I am not convinced it makes sense to remove formatting from WebVTT since, generally, WebVTT is selected when more control over styling is desired

- implementing systemwide formatting filters is not straightforward

I proposed instead adding a `text_formatting` option to SRT writer that allows text formatting to be disabled in SRT output alone.

**Comment by palemieux** [comment]
`tt convert -i <.ttml file> -o <.srt file> --config '{"stl_reader": {"text_formatting": false }}'`

**Comment by andreastai** [comment]
> `tt convert -i <.ttml file> -o <.srt file> --config '{"stl_reader": {"text_formatting": false }}'`

I assume this should read:

`tt convert -i <.ttml file> -o <.srt file> --config '{"srt_writer": {"text_formatting": false }}'`

**Comment by palemieux** [comment]
@andreastai Thanks for the eagle eye!
